# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7z020clg484-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Natalie/Documents/GitHub/rm-star/demoDDS/demoDDS/demoDDS.cache/wt [current_project]
set_property parent.project_path C:/Users/Natalie/Documents/GitHub/rm-star/demoDDS/demoDDS/demoDDS.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:zc702:part0:1.1 [current_project]
add_files -quiet C:/Users/Natalie/Documents/GitHub/rm-star/demoDDS/demoDDS/demoDDS.runs/dds_compiler_0_synth_1/dds_compiler_0.dcp
set_property used_in_implementation false [get_files C:/Users/Natalie/Documents/GitHub/rm-star/demoDDS/demoDDS/demoDDS.runs/dds_compiler_0_synth_1/dds_compiler_0.dcp]
read_vhdl -library xil_defaultlib {
  C:/Users/Natalie/Downloads/ug937/sources/debounce.vhd
  C:/Users/Natalie/Documents/GitHub/rm-star/demoDDS/demoDDS/demoDDS.srcs/sources_1/new/top.vhd
}
read_xdc C:/Users/Natalie/Documents/GitHub/rm-star/demoDDS/demoDDS/demoDDS.srcs/constrs_1/new/zed.xdc
set_property used_in_implementation false [get_files C:/Users/Natalie/Documents/GitHub/rm-star/demoDDS/demoDDS/demoDDS.srcs/constrs_1/new/zed.xdc]

catch { write_hwdef -file top.hwdef }
synth_design -top top -part xc7z020clg484-1
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
